spring:
  application:
    name: monitoring
  #    h2:
  #      console:
  #        enabled: true
  #        path: /h2
  #  datasource:
  #        url: jdbc:h2:mem:test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/bms?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&charSet=utf8mb4
    url: jdbc:mysql://k9a201.p.ssafy.io/almighty?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&charSet=utf8mb4
    username: root
#    password: ssafy
    password: "almighty201"

  data:
    mongodb:
      host: k9a201.p.ssafy.io
      port: 27017
      database: bms
    redis:
      repositories:
        enabled: false
  redis:
    host: www.batteryalmighty.co.kr
    password: almighty201
    port: 6379

#  hikari:
#      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "a201almighty@gmail.com"
    password: "ehopnqerxfvxkbmc"
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql

bms:
  url: http://localhost:8085

logging:
  level:
    com.example : DEBUG
jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4= # ??? ???? Base64? ???? ?
  refresh-token-validity-in-seconds: 1209600 # 14?
  access-token-validity-in-seconds: 43200 # 12??
openai:
  api:
    # key: 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
    key: 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