spring:
  application:
    name: monitoring
    h2:
      console:
        enabled: true
        path: /h2
  datasource:
        url: jdbc:h2:mem:test
  hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    com.example : DEBUG
